name: chat
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  dynamic_color: ^1.6.2
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.9
  flutter:
    sdk: flutter
  image_picker: ^0.8.6+3
  image_cropper: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
